title = "FastSignal"  # From Git
gitRepoUrl = "https://gitlab.com/RBLXUtils/FastSignal" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = ["ScriptSignal", "ScriptConnection"]

[home]
enabled = false
includeReadme = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "RBLXUtils"
projectName = "FastSignal"
url = "https://rblxutils.github.io"
baseUrl = "/FastSignal"
tagline = "Made with consistency and familiarity in mind"

[footer]
style = "dark"